---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - volsync-secret.sops.yaml
  - cyberchef
  - hajimari
  - tandoor-recipes
  - foundryvtt
  - py-kms
  - immich
  - kromgo
  - actual
  - vaultwarden
  - homer
  - your_spotify
  - mealie
  - zipline
