---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn/ks.yaml
  - longhorn-extras/ks.yaml
  - volsync
  - snapshot-controller/ks.yaml
  - openebs/ks.yaml
  - csi-driver-nfs/ks.yaml
  - nfs-provisioner/ks.yaml
  - minio/ks.yaml
